{% set version = "0.2.0" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/pygridgen/pygridgen/archive/v{{ version }}.tar.gz
  sha256: cec931b05132113a03860652d71793ee29ad4fb2aa27486b25ac1e11dc5eae25


build:
  number: 1
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - numpy 1.11.*
    - toolchain
  run:
    - python
    - numpy >=1.11
    - gridgen
    - pandas
    - matplotlib
    - pyproj

test:
  requires:
    - pytest
  imports:
    - pygridgen
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygridgen.github.io/pygridgen/
  license:  MIT
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
