{% set version = "0.1.1" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/phobson/pygridgen/archive/{{ version }}.tar.gz
  sha256: 225266bfca1103255c05de56b54edaeaae471721e181c3a5c1178fa4cdcd216e


build:
  number: 0
  skip: True  # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - toolchain
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - gridgen
    - pandas
    - matplotlib
    - pyproj

test:
  requires:
    - pytest
  imports:
    - pygridgen
  commands:
    - conda inspect linkages -p $PREFIX pygridgen  # [not win]
    - conda inspect objects -p $PREFIX pygridgen  # [osx]

about:
  home: https://github.com/hetland/pygridgen
  license:  MIT
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
