{% set version = "v0.2.0" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/pygridgen/pygridgen/archive/{{ version }}.tar.gz
  sha256: cec931b05132113a03860652d71793ee29ad4fb2aa27486b25ac1e11dc5eae25


build:
  number: 1
  skip: True  # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - toolchain
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - gridgen
    - pandas
    - matplotlib
    - pyproj

test:
  requires:
    - pytest
  imports:
    - pygridgen
  commands:
    - conda inspect linkages -p $PREFIX pygridgen  # [not win]
    - conda inspect objects -p $PREFIX pygridgen  # [osx]

about:
  home: https://pygridgen.github.io/pygridgen/
  license:  MIT
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
