{% set version = "0.2.1" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/pygridgen/pygridgen/archive/v{{ version }}.tar.gz
  sha256: f6cb3d1b8228d38ed215015244f4e1b7e0bef15e9eda33ed8417d5c71c0e24be


build:
  number: 3
  skip: True  # [win or py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gridgen
    - matplotlib-base
    - pyproj

test:
  requires:
    - pytest
  imports:
    - pygridgen

about:
  home: https://pygridgen.readthedocs.io/
  license:  MIT
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
