{% set version = "0.3.0" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/pygridgen/pygridgen/archive/v{{ version }}.tar.gz
  sha256: a38903708ec673ae3dc0b13cb8631ae57c7877a28967f803976a758a96b491fb
  # patches:
  #   - 0001-Fix-compatibility-for-numpy-2.0.patch


build:
  number: 0
  skip: True  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - gridgen
    - matplotlib-base
    - pyproj
    - setuptools

test:
  requires:
    - pytest
  imports:
    - pygridgen

about:
  home: https://pygridgen.readthedocs.io/
  license:  MIT
  license_file: LICENSE.txt
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
