{% set version = "0.2.1" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/pygridgen/pygridgen/archive/v{{ version }}.tar.gz
  sha256: f6cb3d1b8228d38ed215015244f4e1b7e0bef15e9eda33ed8417d5c71c0e24be
  patches:
    - 0001-Fix-compatibility-for-numpy-2.0.patch


build:
  number: 9
  skip: True  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - gridgen
    - matplotlib-base
    - pyproj
    - setuptools

test:
  requires:
    - pytest
  imports:
    - pygridgen

about:
  home: https://pygridgen.readthedocs.io/
  license:  MIT
  license_file: LICENSE.txt
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
