{% set version = "0.2.1" %}

package:
  name: pygridgen
  version: {{ version }}

source:
  url: https://github.com/pygridgen/pygridgen/archive/v{{ version }}.tar.gz
  sha256: f6cb3d1b8228d38ed215015244f4e1b7e0bef15e9eda33ed8417d5c71c0e24be


build:
  number: 0
  skip: True  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gridgen
    - matplotlib
    - pyproj

test:
  requires:
    - pytest
  imports:
    - pygridgen
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://pygridgen.readthedocs.io/
  license:  MIT
  summary: Python interface to gridgen by Pavel Sakov

extra:
  recipe-maintainers:
    - ocefpaf
    - phobson
