travis:
  secure:
    BINSTAR_TOKEN: XiaKJigZ9p456JvfqUZV7yTx6GYTOQG+birfZtu6ZqUv+cjUWlU/0V9+eZ2lSxlz0qGkapkB2k6Cn+v1HgPau0JW3k93CWko71SYvoWspjd/j2xHoaGG+U4R+AaIu8Y7onSrM6mfRvnMZ7un84cfpSHMIDPR0zwFR2X1IwDcLZyMp3UHzaQoWW8lqn0pRkkTWYBlwr6rtKFrYX8pYCUMsWvJgwTx+JTHkwlfv3q1HbOKju8+euSt3Sbg2KvyTge0gbxpbsccWhrPC50gNXhOw9Lfc8Hv4ZEb3ZuQvRl9k9IViZGvuMJqm3wsEMVGi00TSAN3peEn64vGzWQkc2Et6GI3kiodxiQnUSMZ/nIWZg42oKfZCTdPtCTwVg0aI1Ibol64+B97xXDK/acaMl/eKYRNzjEPRqxiS9NaFSGl0p8Mt/6dqaYVhPcTZB0L1vkwNTYCrQnqrv9zWyPJp7n5VxTIDmoPcndQNBuP0TMRMezCL997hdgqk2mkls+LL1rfQtJIjv9o9I6+dYzjxETM4a/1/pfztyExfSVSWJEFGKboEIFHA+epJvgFMbu84t5RFol+F4cZ6nrat6LAdpHFiKXdoSQ7itD6g0kRUBrDCZaizganNh5HafFw9ja6thWWKvTJxexkINaWBystgZWZybjzJUjM2fcG2Q0qy8CngdU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
