appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rO1QTvaYXSUCSznAFwUluVNieWMBbnlJiAPacMgIxOFCk/tU59sPbZm6sqrC1Y7cpoy4wXZXgD6sFsc08irZBkb5cv8nXqSJ3ycFME5EjZEtssapJxu/pvATVwKkHPGUo5pmVtmubKDHJute98qwpvga4cksVOqmKWHwnWxUReZALB+Y0p5QE2U+5K67aZ2Kjn9uJAdLSgH7oCKko05+J4wxOMFSlFkXmRxTcy8z9xNJ+V2ku2h8alZBwPwBEDSHYMVdLys2Vygv3mXLHySUX6f6ZzINaR4qfgE7xlxs7l4sAicXGg1spztWCCKabu3hSfEtiggh1IkX1+mCtcQOrJ1E4D6LqJEpMLHEuVXhsECupriEWC0tL+IUtJPJoFCoa26UgcyvZ0UGJiCYfikmZxozxd+FFSNWfgKgd6jWQj+5dUh0u/ANlI0pCACMCxB3k0HR8Qh+0AIuGbHkjjDn8LUVXXlI/lLx0BBCTUGq10+toNGNqRE9wYwqlu8NanCT0dd7iqKtoXODXIF6d1SvGlDrxmjlf/7Fye880ox27ZEUdKqqemCF1BwXJqj/UI2JYzXBMnWp2SMebktkQ23L3V8gT2zrI74elkc7kiiD3aVrGOO7fgmMtv/5YAFdALTdCg7t1/j2/Hy0WCKnbx3uyOuXrryPHnAmdfC0uGKHV7w=}
conda_forge_output_validation: true
